jwplayer("player").setup({ 
'playlist': [

{'sources': [{'file': 'http://118.97.167.19/jhos/allegro//Playlist.m3u8'}],
'title': 'ALLEGRO',
'description': '',
'image': 'http://images.useetv.com/logo_allegro_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.8/jhos/allegro/Playlist.m3u'}],
'title': 'ALLEGRO',
'description': '',
'image': 'http://images.useetv.com/logo_allegro_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.8/jhos/antv//Playlist.m3u8'}],
'title': 'ANTV',
'description': '',
'image': 'http://images.useetv.com/logo_antv_big1.png',
'mediaid': ''},

{'sources': [{'file': 'http://118.97.167.8/jhos/rtv//Playlist.m3u8'}],
'title': 'RTV',
'description': '',
'image': 'http://www.aora.tv/aora-files/images/channel/51df0902-1e1b-fc2d-8189-535eb829aba0.jpg',
'mediaid': ''},
{'sources': [{'file': 'http://180.250.29.12/jhos/indosiar_3//Playlist.m3u8'}],
 'title': 'INDOSIAR',
 'description': '', 
'image': 'http://images.useetv.com/logo_indosiar_big2.png',
 'mediaid': ''},

{'sources': [{'file': 'http://118.97.167.8/jhos/kompastv//Playlist.m3u8'}],
'title': 'KOMPASTV',
'description': '',
'image': 'http://images.useetv.com/logo_kompastv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://180.250.29.12/jhos/metrotv_3/Playlist.m3u8'}],
'title': 'METROTV',
'description': '',
'image': 'http://images.useetv.com/logo_metrotv_big2.png',
'mediaid': ''},

{'sources': [{'file': 'http://180.250.29.12/jhos/sctv_3/Playlist.m3u8'}],
'title': 'SCTV',
'description': '',
'image': 'http://images.useetv.com/logo_sctv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.8/jhos/tvone//Playlist.m3u8'}],
'title': 'TVONE',
'description': '',
'image': 'http://images.useetv.com/logo_tvone_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/ochannel/Playlist.m3u8'}],
'title': 'QCHANEL',
'description': '',
'image': 'http://images.useetv.com/logo_ochannel_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/balitv/Playlist.m3u8'}],
'title': 'BALITV',
'description': '',
'image': 'http://images.useetv.com/logo_balitv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/tvri/Playlist.m3u8'}],
'title': 'TVRI',
'description': '',
'image': 'http://images.useetv.com/sharp-tvri.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/tvedukasi/Playlist.m3u8'}],
'title': 'tvedukasi',
'description': '',
'image': 'http://images.useetv.com/sharp-tvedukasi.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/alquran/Playlist.m3u8'}], 
'title': 'alquran', 
'description': '',
 'image': 'http://images.useetv.com/sharp-alquran.png', 
'mediaid': ''}, 
{'sources': [{'file': 'http://118.97.167.19/jhos/arena/Playlist.m3u8'}],
'title': 'arena',
'description': '',
'image': 'http://images.useetv.com/sharp-arena.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/aljazeera/Playlist.m3u8'}],
'title': 'aljazeera',
'description': '',
'image': 'http://images.useetv.com/sharp-aljazeera.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/celebestv/Playlist.m3u8'}],
'title': 'celebestv',
'description': '',
'image': 'http://images.useetv.com/sharp-celebestv.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/mqtv/Playlist.m3u8'}],
'title': 'mqtv',
'description': '',
'image': 'http://images.useetv.com/logo_mqtv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/tauhidtv/Playlist.m3u8'}],
'title': 'tauhidtv',
'description': '',
'image': 'http://images.useetv.com/logo_tauhidtv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/beritasatu/Playlist.m3u8'}],
'title': 'beritasatu',
'description': '',
'image': 'http://images.useetv.com/logo_beritasatu_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/aliftv/Playlist.m3u8'}],
'title': 'aliftv',
'description': '',
'image': 'http://images.useetv.com/logo_aliftv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/jtv/Playlist.m3u8'}],
'title': 'jtv',
'description': '',
'image': 'http://images.useetv.com/logo_jtv_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/muhammadiyahtv/Playlist.m3u8'}],
'title': 'tvmuhammadiyah',
'description': '',
'image': 'http://images.useetv.com/logo_tvmuhammadiyah_big2.png',
'mediaid': ''},
{'sources': [{'file': 'http://118.97.167.19/jhos/tempotv/Playlist.m3u8'}],
'title': 'tempotv',
'description': '',
'image': 'http://images.useetv.com/logo_tempotv_big2.png',
'mediaid': ''},
{'sources': [{'file': '\x68\x74\x74\x70\x3a\x2f\x2f\x6c\x69\x76\x65\x2e\x6d\x79\x74\x72\x61\x6e\x73\x2e\x63\x6f\x6d\x2f\x6c\x69\x76\x65\x2f\x74\x72\x61\x6e\x73\x74\x76\x2e\x73\x64\x70\x2f\x70\x6c\x61\x79\x6c\x69\x73\x74\x2e\x6d\x33\x75\x38'}],
'title': 'tempotv',
'description': '',
'image': 'http://images.useetv.com/logo_tempotv_big2.png',
'mediaid': ''},

],
layout: 'basic',
listbar: {position: 'right',size: 220 },
logo: {file: "http://3.bp.blogspot.com/-UPXteOoEtAg/U3WunexRi1I/AAAAAAAABO8/oMVvRj3DSI0/s1600/WAROHOTV.png",position: 'top-right',margin: '0',link: "http://warohotv.blogspot.com/"},
stretching: "exactfit",
skin: "roundster",
width: '100%',
height: '100%',
 plugins: {   'http://luwes.co/lightsout-jw/2.0/lightsout.js':{            onplay:     'on',            onpause:    'on',            oncomplete: 'on',            dockicon: true,            onidle: 'on'         }  },

sharing: {code: encodeURI("<iframe width='600' height='500' src='http://playerwaroho.blogspot.com/2014/05/1238.html' /></iframe>"),link: "http://warohotv.blogspot.com/" }
});